version: '3.8'
services:
  aws-cdk:
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    volumes:
      - .:/code
    environment:
      PROJECT_NAME: ${PROJECT_NAME}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
